const tableData = [
  {
    id: 1,
    first_name: "Temitope",
    location: "Festac",
    last_name: "Adejumoke",
    phone_number: " +234800 000 0000",
    partner: "Xpress Rewards",
    status: "Active",
    action: "default",
  },
  {
    id: 2,
    first_name: "Temitope",
    location: "Festac",
    last_name: "Adejumoke",
    phone_number: " +234800 000 0000",
    partner: "Xpress Rewards",
    status: "Awaiting approval",
    action: "default",
  },
  {
    id: 4,
    first_name: "Temitope",
    location: "Festac",
    last_name: "Adejumoke",
    phone_number: " +234800 000 0000",
    partner: "Xpress Rewards",
    status: "Deactivated",
    action: "default",
  },
  {
    id: 1,
    first_name: "Temitope",
    location: "Festac",
    last_name: "Adejumoke",
    phone_number: " +234800 000 0000",
    partner: "Xpress Rewards",
    status: "Active",
    action: "default",
  },
  {
    id: 3,
    first_name: "Temitope",
    location: "Festac",
    last_name: "Adejumoke",
    phone_number: " +234800 000 0000",
    partner: "Xpress Rewards",
    status: "Active",
    action: "default",
  },
  {
    id: 5,
    first_name: "Temitope",
    location: "Festac",
    last_name: "Adejumoke",
    phone_number: " +234800 000 0000",
    partner: "Xpress Rewards",
    status: "Active",
    action: "default",
  },
  {
    id: 6,
    first_name: "Temitope",
    location: "Festac",
    last_name: "Adejumoke",
    phone_number: " +234800 000 0000",
    partner: "Xpress Rewards",
    status: "Awaiting approval",
    action: "default",
  },
  {
    id: 3,
    first_name: "Temitope",
    location: "Festac",
    last_name: "Adejumoke",
    phone_number: " +234800 000 0000",
    partner: "Xpress Rewards",
    status: "Active",
    action: "default",
  },
  {
    id: 4,
    first_name: "Temitope",
    location: "Festac",
    last_name: "Adejumoke",
    phone_number: " +234800 000 0000",
    partner: "Xpress Rewards",
    status: "Deactivated",
    action: "default",
  },
  {
    id: 3,
    first_name: "Temitope",
    location: "Festac",
    last_name: "Adejumoke",
    phone_number: " +234800 000 0000",
    partner: "Xpress Rewards",
    status: "Active",
    action: "default",
  },
  {
    id: 5,
    first_name: "Temitope",
    location: "Festac",
    last_name: "Adejumoke",
    phone_number: " +234800 000 0000",
    partner: "Xpress Rewards",
    status: "Active",
    action: "default",
  },
  {
    id: 6,
    first_name: "Temitope",
    location: "Festac",
    last_name: "Adejumoke",
    phone_number: " +234800 000 0000",
    partner: "Xpress Rewards",
    status: "Awaiting approval",
    action: "default",
  },
];

export default tableData;
